/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>

#define SRAM_ADDR	0x20000004UL
int main(void)
{
	uint32_t value=0;
	uint32_t *p = (uint32_t *)SRAM_ADDR;
	while(1){
		value=*p;
		if(value) break;
	}


	for(;;);
}

