/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>
void delay_ms() {
    for (uint32_t i = 0; i <500000;i++);
}
int main(void)
{
	uint32_t *pClkctrlreg =(uint32_t*)0x40021018;
	uint32_t *pPortDmodereg =(uint32_t*)0x40011004;
	uint32_t *pPortDoutreg =(uint32_t*)0x4001100C;



	//set clock to 1(pin 12) GPIOD and GPIOA
	*pClkctrlreg |=(1<<4);
	//*pClkctrlreg |=0x1;
	//set mode to 01 general output
	*pPortDmodereg &= ~(0xF << 20); ;
	*pPortDmodereg  |= (0x1 << 20);
	//setting input mode for GPIOA
	while(1){
	*pPortDoutreg |=(1 << 13);
	delay_ms();
	printf("LED ON");
	*pPortDoutreg &=~(1 << 13);
	delay_ms();
	printf("LED OFF");

	}






}
