/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>
#include "main.h"
void delay_ms(uint32_t ms) {
    for (uint32_t i = 0; i < ms * 8000; i++);
}
int main(void)
{
	RCC_AHB1ENR_t volatile *const pClckctrlreg = (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODE_t volatile *const pPortDmodereg =(GPIOx_MODE_t*)0x40020C00;
	GPIOx_ORD_t volatile *const pPortDoutreg =(GPIOx_ORD_t*)0x40020C14;

	pClckctrlreg->gpioden=1;
	pPortDmodereg->moder12=1;
	while(1){
		for(uint32_t i=0;i<1000000;i++);
		pPortDoutreg->ot12=1;
		for(uint32_t i=0;i<1000000;i++);
		pPortDoutreg->ot12=0;

	}


}
