/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
int main(void)
{
	int a;
	a=24;

	int b=32;
	int sum;
	sum=a+b;
	printf("The value of a is %d",sum);


	for(;;);
}

