/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>
void delay(){
	for(uint32_t i=0;i<30000;i++);
}

int main(void)
{
	uint32_t volatile *const pClkctrlreg = (uint32_t *)0x40023830;
	uint32_t volatile *const pPortDmodereg = (uint32_t *)0x40020C00;
	uint32_t volatile *const pOutModeDreg =(uint32_t *)0x40020C14;
	uint32_t volatile *const pINModeDreg =(uint32_t *)0x40020C10;
	uint32_t volatile *const pPullUpDownreg =(uint32_t *)(0x40020C00+0x0C);
	//enabling clock for port D register
	*pClkctrlreg |=(1<<3);
	//enabling mode register for PD0-PD3 and PD8-PD11
	*pPortDmodereg &=~(0xFF);
	*pPortDmodereg |=(0x55);
	*pPortDmodereg &=~(0xFF<<16);

	//adding pull up register
	*pPullUpDownreg &=~(0xFF<<16);
	*pPullUpDownreg |=(0x55<<16);
while(1){
	//making all rows high
	*pOutModeDreg |=(0x0F);
	//make R1 low
	*pOutModeDreg &=~(1<<0);
	//check for c1
	if(!(*pINModeDreg & (1<<8))){
		delay();
		printf("1\n");
		break;
	}
	if(!(*pINModeDreg & (1<<9))){
			delay();
			printf("2\n");
			break;
		}
	if(!(*pINModeDreg & (1<<10))){
			delay();
			printf("3\n");
			break;
		}
	if(!(*pINModeDreg & (1<<11))){
			delay();
			printf("A\n");
			break;
		}
	//making all rows high
		*pOutModeDreg |=(0x0F);
		//make R2 low
		*pOutModeDreg &=~(1<<1);
		//check for c1
		if(!(*pINModeDreg&(1<<8))){
			delay();
			printf("4\n");
			break;
		}
		if(!(*pINModeDreg & (1<<9))){
				delay();
				printf("5\n");
				break;
			}
		if(!(*pINModeDreg & (1<<10))){
				delay();
				printf("6\n");
				break;
			}
		if(!(*pINModeDreg & (1<<11))){
				delay();
				printf("B\n");
				break;
			}
      //making all rows high
			*pOutModeDreg |=(0x0F);
			//make R3 low
			*pOutModeDreg &=~(1<<2);
			//check for c1
			if(!(*pINModeDreg&(1<<8))){
				delay();
				printf("7\n");
				break;
			}
			if(!(*pINModeDreg & (1<<9))){
					delay();
					printf("8\n");
					break;
				}
			if(!(*pINModeDreg & (1<<10))){
					delay();
					printf("9\n");
					break;
				}
			if(!(*pINModeDreg & (1<<11))){
					delay();
					printf("C\n");
					break;
				}
			//making all rows high
				*pOutModeDreg |=(0x0F);
				//make R4 low
				*pOutModeDreg &=~(1<<3);
				//check for c1
				if(!(*pINModeDreg & (1<<8))){
					delay();
					printf("*\n");
					break;
				}
				if(!(*pINModeDreg & (1<<9))){
						delay();
						printf("0\n");
						break;
					}
				if(!(*pINModeDreg & (1<<10))){
						delay();
						printf("#\n");
						break;
					}
				if(!(*pINModeDreg & (1<<11))){
						delay();
						printf("D\n");
						break;
					}
}



}

