/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>
int main(void)
{
	uint32_t *pClkctrlreg =(uint32_t*)0x40023830;
	uint32_t *pPortDmodereg =(uint32_t*)0x40020C00;
	uint32_t *pPortDoutreg =(uint32_t*)0x40020C14;
	uint32_t *pPortAModereg =(uint32_t*)0x40020000;
	uint32_t *pPortAINreg =(uint32_t*)0x40020010;


	//set clock to 1(pin 12) GPIOD and GPIOA
	*pClkctrlreg |=0x08;
	//*pClkctrlreg |=0x1;
	//set mode to 01 general output
	*pPortDmodereg &=0x00FFFFFF;
	*pPortDmodereg |=0x55000000;
	//setting input mode for GPIOA
	*pPortDoutreg |=0xF000;






}

