/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>
void delay();
int main(void)
{
	uint32_t volatile * const pClkctrlreg =(uint32_t*)0x40023830;
	uint32_t volatile * const pPortDmodereg =(uint32_t*)0x40020C00;
	uint32_t volatile * const pPortDoutreg =(uint32_t*)0x40020C14;
	uint32_t volatile * const pPortInmodereg =(uint32_t*)(0x40020C00+0x10);
	uint32_t volatile * const pPullupdownreg = (uint32_t*)(0x40020C00+0x0C);
	//clock enable
	*pClkctrlreg |=(0x08);
	//setting input for rows 0-3
	*pPortDmodereg &=~(0xFF<<16);
	//setting output for column
	*pPortDmodereg &=~(0xFF);
	*pPortDmodereg |=(0x55);
	//setting pull up register
	*pPullupdownreg &=~(0xFF<<16);
	*pPullupdownreg |=(0x55<<16);
	//setting a loop for checking the key pressed
	while(1){
		//setting all rows high
		*pPortDoutreg |=(0xF);
		//setting row1 low
		*pPortDoutreg &=~(1<<0);
		//checking column
		if(!(*pPortInmodereg |=(0x0<<8))){
			//key 1 pressed
			delay();
			printf("%d\n",1);
		}
		if(!(*pPortInmodereg |=(0x0<<9))){
			//key 2 pressed
			delay();
			printf("%d\n",2);
		}
		if(!(*pPortInmodereg |=(0x0<<8))){
			//key 3 pressed
			delay();
			printf("%d\n",3);
		}
		if(!(*pPortInmodereg |=(0x0<<8))){
			//key A pressed
			delay();
			printf("%c\n",65);
		}
		//setting all rows high
		*pPortDoutreg |=(0xF);
		//setting row2 low
		*pPortDoutreg &=~(1<<1);
		//checking column
		if(!(*pPortInmodereg |=(0x0<<8))){
			//key 4 pressed
			delay();
			printf("%d\n",4);
		}
		if(!(*pPortInmodereg |=(0x0<<9))){
			//key 5 pressed
			delay();
			printf("%d\n",5);
		}
		if(!(*pPortInmodereg |=(0x0<<8))){
			//key 6 pressed
			delay();
			printf("%d\n",6);
		}
		if(!(*pPortInmodereg |=(0x0<<8))){
			//key B pressed
			delay();
			printf("%c\n",66);
		}
		*pPortDoutreg |=(0xF);
				//setting row3 low
				*pPortDoutreg &=~(1<<2);
				//checking column
				if(!(*pPortInmodereg |=(0x0<<8))){
					//key 7 pressed
					delay();
					printf("%d\n",7);
				}
				if(!(*pPortInmodereg |=(0x0<<9))){
					//key 8 pressed
					delay();
					printf("%d\n",8);
				}
				if(!(*pPortInmodereg |=(0x0<<8))){
					//key 9 pressed
					delay();
					printf("%d\n",9);
				}
				if(!(*pPortInmodereg |=(0x0<<8))){
					//key  C pressed
					delay();
					printf("%c\n",67);
				}
		*pPortDoutreg |=(0xF);
				//setting row2 low
				*pPortDoutreg &=~(1<<3);
				//checking column
				if(!(*pPortInmodereg |=(0x0<<8))){
					//key * pressed
					delay();
					printf("%c\n",42);
				}
				if(!(*pPortInmodereg |=(0x0<<9))){
					//key 5 pressed
					delay();
					printf("%d\n",0);
				}
				if(!(*pPortInmodereg |=(0x0<<8))){
					//key 6 pressed
					delay();
					printf("%c\n",35);
				}
				if(!(*pPortInmodereg |=(0x0<<8))){
					//key B pressed
					delay();
					printf("%c\n",68);
				}


	}
}
void delay(void){
	for(uint32_t i=0;i<30000;i++);
}
